### ISSUE TITLE
vault 1.5.x < 1.5.4 reports incorrect version

### ISSUE THREAD

**Issue by aieri** [canonical/snap-vault#26] opened 2020-09-14 16:29 UTC
Vault just got refreshed to version 1.5.3, but something must have gone wrong with the snap build:

```
# snap list vault
Name   Version  Rev   Tracking       Publisher   Notes
vault  1.5.3    1930  latest/stable  canonical✓  -

# curl -s http://127.0.0.1:8220/v1/sys/health?standbyok=true | jq '.version'
"1.5.0"

# /snap/vault/current/bin/vault --version
Vault v1.5.0 (cgo)
```

**Comment by afreiberger** [comment] 2020-09-14 16:37
This is due to upstream missing minor rev update:

https://github.com/hashicorp/vault/blob/v1.5.3/sdk/version/version_base.go#L11

This is also set to the same 1.5.0 string as in the releases/1.5.x branch.

Bug should be sent upstream to hashicorp.

**Comment by afreiberger** [comment] 2020-09-14 16:38
I'm also thinking that this repo should reference the 1.5.3 tag in snapcraft.yaml rather than the modifiable releases/1.5.x branch.

**Comment by aieri** [comment] 2020-09-14 16:48
[Done](https://github.com/hashicorp/vault/issues/9943).

It may be worth leaving this issue open to track needing to rebuild the snap as soon as 1.5.4 will be out.

**Comment by taodd** [comment] 2020-09-29 07:01
The issue is fixed in vault 1.5.4 and was just got released, need to rebuild the snap with this version

**Comment by javacruft** [comment] 2020-09-29 09:27
1.5.4 in candidate for testing

**Comment by javacruft** [comment] 2020-09-29 10:33
1.5.4 released to stable channel

**Closed by javacruft** 2020-09-29 10:33 UTC
